version: "3.8"

services:
  frontend:
    build: ./client
    ports:
      - 3000:3000
  backend:
    build: ./server
    ports:
      - 5000:5000
    environment:
      MONGO_URL: "mongodb://database/VRS"

  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:  
      - VRS:/data/db

volumes:
  VRS:   